spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/testone
      username: devone
      password: devoneb
      platform: postgresql
      initialization-mode: always
mytest:
   name: murali-alpha

